# Use the official Node.js image
FROM node:16

# Install ffmpeg
RUN apt-get update && apt-get install -y ffmpeg

# Create and change to the app directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY recorder/package*.json ./

# Install dependencies
RUN npm install

# Copy the recorder script
COPY recorder/recorder.js ./

# Ensure the audio directory exists
RUN mkdir -p /usr/src/app/audio

# Command to run the recorder script
CMD ["node", "recorder.js"]
